export const appName = "MS Diagnosis";

export const navLinks = [
  { path: "/", label: "Home" },
  { path: "/diagnosis", label: "Diagnosis" },
  { path: "/remedies", label: "Remedies" },
  { path: "/consultation", label: "Consultation" },
  // { path: "/contact", label: "Contact" },
];

export const consulationService = [
  {
    name: "AIIMS, Delhi (Neurology Dept.)",
    city: "New Delhi",
    contact: "+91-11-26588500",
    type: "Offline",
    services:
      "Dedicated Multiple Sclerosis clinic offering comprehensive diagnosis and treatment.",
    rating: 4.2,
    website: "https://aiims.edu",
    color: "from-blue-500 to-blue-600",
    bgColor: "bg-blue-50",
    borderColor: "border-blue-200",
  },
  {
    name: "Max Institute of Neurosciences",
    city: "New Delhi",
    contact: "+91-11-66115050",
    type: "Offline",
    services:
      "Exclusive MS clinic with expert neurologists, advanced diagnostics and therapies.",
    rating: null,
    website: "https://www.maxhealthcare.in",
    color: "from-purple-500 to-purple-600",
    bgColor: "bg-purple-50",
    borderColor: "border-purple-200",
  },
  {
    name: "Metro Hospital & Heart Institute",
    city: "Noida (NCR Delhi)",
    contact: "+91-120-4366666 / +91-120-2533491",
    type: "Offline",
    services:
      "Dedicated MS clinic with comprehensive diagnostics and treatments.",
    rating: null,
    website: "https://metrohospitals.com",
    color: "from-teal-500 to-teal-600",
    bgColor: "bg-teal-50",
    borderColor: "border-teal-200",
  },
  {
    name: "NIMHANS (Neuro Sciences Dept.)",
    city: "Bangalore",
    contact: "+91-80-26995000",
    type: "Offline",
    services:
      "Premier institute providing full-spectrum neurological care including MS.",
    rating: null,
    website: "https://nimhans.ac.in",
    color: "from-indigo-500 to-indigo-600",
    bgColor: "bg-indigo-50",
    borderColor: "border-indigo-200",
  },
  {
    name: "Kauvery Hospital (Neuroscience)",
    city: "Chennai",
    contact: "+91-44-61116111 / +91-44-40006000",
    type: "Offline",
    services:
      "MS-focused neurology team with fatigue clinic and therapy packages.",
    rating: null,
    website: "https://www.kauveryhospital.com",
    color: "from-cyan-500 to-cyan-600",
    bgColor: "bg-cyan-50",
    borderColor: "border-cyan-200",
  },
  {
    name: "CARE Hospitals (Banjara Hills)",
    city: "Hyderabad",
    contact: "+91-40-68106529",
    type: "Offline",
    services:
      "Comprehensive MS care: diagnostics, therapies, and rehabilitation.",
    rating: 4.4,
    website: "https://www.carehospitals.com",
    color: "from-orange-500 to-orange-600",
    bgColor: "bg-orange-50",
    borderColor: "border-orange-200",
  },
  {
    name: "MSSI – Chennai Chapter",
    city: "Chennai",
    contact: "044-66240358 / 9884314021",
    type: "Offline",
    services:
      "Home physio, counseling, neurologist referrals, and support aids.",
    rating: null,
    website: "https://www.mssocietyindia.org",
    color: "from-green-500 to-green-600",
    bgColor: "bg-green-50",
    borderColor: "border-green-200",
  },
  {
    name: "MSSI – Mumbai Chapter",
    city: "Mumbai",
    contact: "+91-22-24037390 / +91-22-24037399",
    type: "Offline",
    services:
      "Nursing, free meds, counseling, disability help, funding support.",
    rating: null,
    website: "https://www.mssocietyindia.org",
    color: "from-pink-500 to-pink-600",
    bgColor: "bg-pink-50",
    borderColor: "border-pink-200",
  },
  {
    name: "MSSI – Bengaluru Chapter",
    city: "Bengaluru",
    contact: "+91-80-22992626 / +91-9945012626",
    type: "Offline",
    services: "Bi-monthly support group, education, psychosocial care.",
    rating: null,
    website: "https://www.mssocietyindia.org",
    color: "from-violet-500 to-violet-600",
    bgColor: "bg-violet-50",
    borderColor: "border-violet-200",
  },
  {
    name: "MSSI – Hyderabad Chapter",
    city: "Hyderabad",
    contact: "+91-93900-55598",
    type: "Offline",
    services: "Physiotherapy, counseling, home visits, mobility aids.",
    rating: null,
    website: "https://www.mssocietyindia.org",
    color: "from-emerald-500 to-emerald-600",
    bgColor: "bg-emerald-50",
    borderColor: "border-emerald-200",
  },
];
